---
- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: restart sensu-server
  service:
    name: sensu-server
    state: restarted

- name: restart uchiwa
  service:
    name: uchiwa
    state: restarted
